blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/pedroproenca/designer-feedback/discussions
    about: Use discussions for questions, ideas, and general conversation
